name: Release Bot

on:
  release:
    types: [published]

jobs:
  create_release_blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout consumer repository
        uses: actions/checkout@v4

      - name: AI-Release-Bot
        uses: octo-pie-admin/release-bot@main
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          llm_model: ${{ secrets.LLM_MODEL }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          release_tag: ${{ github.event.release.tag_name || 'latest' }}
          openapi_file: ${{ secrets.OPENAPI_FILE || 'not_real' }}
