name: Octo-Pie-Release-Bot (Local Test)

on:
  # never runs in CI automatically — only manual trigger
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      # defaults so act works without needing real secrets
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN || 'test-token' }}
      GITHUB_REPOSITORY: ${{ github.repository || 'example-org/example-repo' }}
      ACT: ${{ secrets.ACT || 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Octo-Pie-Release-Bot
        uses: ./  # local action
        id: AI-Release-Bot
        with:
          github_token: ${{ secrets.GITHUB_TOKEN || 'test-token' }}
          llm_model: ${{ secrets.LLM_MODEL || 'gpt-4o-mini' }}
          llm_url: ${{ secrets.LLM_URL || 'http://localhost:11434/v1' }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY || 'sk-test' }}
          release_tag: ${{ github.event.release.tag_name || 'latest' }}
          openapi_file: ./tests/openapi.json
          output_format: ${{ secrets.OUTPUT_FORMAT || 'jekyll' }}
          act: ${{ secrets.ACT || 'true' }}